// Generated by CoffeeScript 1.3.3
(function() {
  var Artemis, original_Artemis, root;

  root = this;

  original_Artemis = root.Artemis;

  Artemis = void 0;

  if (typeof exports !== "undefined") {
    Artemis = exports;
  } else {
    Artemis = original_Artemis = {};
    root.Artemis = Artemis;
  }

  Artemis.VERSION = "0.0.1";

}).call(this);
