// Generated by CoffeeScript 1.3.3
(function() {
  var Bragi, original_bragi, root;

  root = this;

  original_bragi = root.Bragi;

  Bragi = void 0;

  if (typeof exports !== "undefined") {
    Bragi = exports;
  } else {
    Bragi = original_bragi = {};
    root.Bragi = Bragi;
  }

  Bragi.VERSION = "0.0.1";

}).call(this);
