// Generated by CoffeeScript 1.3.3
(function() {
  var Component;

  Artemis.Component = {};

  Component = (function() {

    function Component() {}

    return Component;

  })();

  Artemis.Component = Component;

}).call(this);
