// Generated by CoffeeScript 1.3.3
(function() {
  var ComponentMapper;

  Bragi.ComponentMapper = {};

  ComponentMapper = (function() {

    function ComponentMapper(componentName, world) {
      this.world = world;
      this.em = world.entityManager;
      this.componentName = componentName;
    }

    ComponentMapper.prototype.get = function(entity) {
      return this.em._getComponent(entity, this.componentName);
    };

    return ComponentMapper;

  })();

  Bragi.ComponentMapper = ComponentMapper;

}).call(this);
