// Generated by CoffeeScript 1.3.3
(function() {
  var ComponentTypeManager;

  Artemis.ComponentTypeManager = {};

  ComponentTypeManager = (function() {
    var _componentTypes;

    function ComponentTypeManager() {}

    _componentTypes = {};

    ComponentTypeManager.getType = function(component) {
      var className, type;
      if (!(component instanceof Artemis.Component)) {
        throw new Error("Tried to add a component that is not inheriting from Component");
      }
      className = component.constructor.name;
      type = _componentTypes[className];
      if (!type) {
        type = new Artemis.ComponentType();
        _componentTypes[className] = type;
      }
      return type;
    };

    ComponentTypeManager.getTypeByName = function(className) {
      var type;
      type = _componentTypes[className];
      if (!type) {
        type = new Artemis.ComponentType();
        _componentTypes[className] = type;
      }
      return type;
    };

    ComponentTypeManager.getId = function(component) {
      return this.getType(component).id;
    };

    ComponentTypeManager.getBit = function(component) {
      return this.getType(component).bit;
    };

    return ComponentTypeManager;

  })();

  Artemis.ComponentTypeManager = ComponentTypeManager;

}).call(this);
