// Generated by CoffeeScript 1.3.3
(function() {
  var ComponentType;

  Artemis.ComponentType = {};

  ComponentType = (function() {
    var _nextBit, _nextId;

    _nextId = 0;

    _nextBit = 1;

    function ComponentType() {
      this.id = _nextId;
      _nextId++;
      this.bit = _nextBit;
      _nextBit = _nextBit << 1;
    }

    return ComponentType;

  })();

  Artemis.ComponentType = ComponentType;

}).call(this);
