// Generated by CoffeeScript 1.3.3
(function() {
  var Entity;

  Bragi.Entity = {};

  Entity = (function() {

    function Entity(world, id) {
      this.world = world;
      this.id = id;
      this.bits = 0;
    }

    Entity.prototype["delete"] = function() {
      return this.world.deleteEntity(this);
    };

    Entity.prototype.addComponent = function(component) {
      if (!(component instanceof Bragi.Component)) {
        throw new Error("Tried to add a component that is not inheriting from Component");
      }
      this.world.entityManager._addComponent(this, component);
      return null;
    };

    Entity.prototype.removeComponent = function(componentName) {
      this.world.entityManager._removeComponent(this, componentName);
      return null;
    };

    Entity.prototype.getComponent = function(componentName) {
      return this.world.entityManager._getComponent(this, componentName);
    };

    Entity.prototype._addBit = function(bit) {
      return this.bits |= bit;
    };

    Entity.prototype._removeBit = function(bit) {
      return this.bits &= ~bit;
    };

    Entity.prototype.isActive = function() {
      return this.world.entityManager._isActive(this.id);
    };

    Entity.prototype.getComponents = function() {};

    return Entity;

  })();

  Bragi.Entity = Entity;

}).call(this);
