// Generated by CoffeeScript 1.3.3
(function() {
  var EntityWorld;

  Bragi.EntityWorld = {};

  EntityWorld = (function() {

    function EntityWorld() {
      this.entityManager = new Bragi.EntityManager(this);
      this.systemManager = new Bragi.SystemManager(this);
      this.tagManager = new Bragi.TagManager(this);
      this.deleted = [];
    }

    EntityWorld.prototype.createEntity = function() {
      return this.entityManager._create();
    };

    EntityWorld.prototype.getEntity = function(id) {
      return this.entityManager._getEntity(id);
    };

    EntityWorld.prototype.deleteEntity = function(entity) {};

    EntityWorld.prototype.getEntityByTag = function(tag) {};

    return EntityWorld;

  })();

  Bragi.EntityWorld = EntityWorld;

}).call(this);
