// Generated by CoffeeScript 1.3.3
(function() {
  var EntityManager;

  Bragi.EntityManager = {};

  EntityManager = (function() {

    function EntityManager(world) {
      this.world = world;
      this.entities = {};
      this.nextId = 0;
    }

    EntityManager.prototype.create = function() {
      var entity;
      entity = new Bragi.Entity(this.world, this.nextId);
      this.nextId++;
      this.entities[entity.id] = entity;
      return entity;
    };

    EntityManager.prototype.remove = function(entity) {
      return delete this.entities[entity.id];
    };

    EntityManager.prototype.addComponent = function(entity, component) {};

    EntityManager.prototype.getComponent = function(entity, component) {};

    EntityManager.prototype.removeComponent = function(entity, component) {};

    EntityManager.prototype.removeAllComponents = function(entity) {};

    EntityManager.prototype.getEntity = function(id) {};

    EntityManager.prototype.isActive = function(id) {};

    return EntityManager;

  })();

  Bragi.EntityManager = EntityManager;

}).call(this);
