// Generated by CoffeeScript 1.3.3
(function() {
  var SystemManager,
    __indexOf = [].indexOf || function(item) { for (var i = 0, l = this.length; i < l; i++) { if (i in this && this[i] === item) return i; } return -1; };

  Bragi.SystemManager = {};

  SystemManager = (function() {
    var _pos, _systemBits;

    _systemBits = {};

    _pos = 0;

    function SystemManager(world) {
      this.world = world;
      this.systems = {};
      this.allSystems = [];
    }

    SystemManager.prototype._getBitFor = function(system) {
      var bit;
      bit = _systemBits[system];
      if (!bit) {
        bit = 1 << _pos;
        _pos += 1;
        _systemBits[system] = bit;
      }
      return bit;
    };

    SystemManager.prototype.addSystem = function(system) {
      system.world = this.world;
      this.systems[system.constructor.name] = system;
      if (__indexOf.call(this.allSystems, system) < 0) {
        this.allSystems.push(system);
      }
      return system.bit = this._getBitFor(system.constructor.name);
    };

    SystemManager.prototype.getSystem = function(type) {
      return this.systems[type];
    };

    SystemManager.prototype.initializeAll = function() {
      var system, _i, _len, _ref, _results;
      _ref = this.allSystems;
      _results = [];
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        system = _ref[_i];
        _results.push(system.initialize());
      }
      return _results;
    };

    SystemManager.prototype.getSystems = function() {};

    return SystemManager;

  })();

  Bragi.SystemManager = SystemManager;

}).call(this);
