// Generated by CoffeeScript 1.3.3
(function() {
  var System;

  Bragi.System = {};

  System = (function() {

    function System() {}

    System.prototype.construct = function() {};

    System.prototype.initialize = function() {};

    return System;

  })();

  Bragi.System = System;

}).call(this);
