// Generated by CoffeeScript 1.3.3
(function() {
  var World;

  Bragi.World = {};

  World = (function() {

    function World() {
      this.entityManager = new Bragi.EntityManager(this);
      this.systemManager = new Bragi.SystemManager(this);
      this.tagManager = new Bragi.TagManager(this);
      this.deleted = [];
    }

    World.prototype.createEntity = function() {
      return this.entityManager.create();
    };

    World.prototype.deleteEntity = function(entity) {};

    World.prototype.getEntity = function(id) {};

    World.prototype.getEntityByTag = function(tag) {};

    return World;

  })();

  Bragi.World = World;

}).call(this);
