// Generated by CoffeeScript 1.3.3
(function() {

  describe("Component Types", function() {
    return describe("Instantiation", function() {
      var type1, type2;
      type1 = null;
      type2 = null;
      before(function() {
        Bragi.ComponentType._nextComponentId = 0;
        Bragi.ComponentType._nextUniqueId = 0;
        type1 = new Bragi.ComponentType();
        return type2 = new Bragi.ComponentType();
      });
      it("first component type should have both componentId and uniqueId equal to 0", function() {
        type1.componentId.should.be.equal(0);
        return type1.uniqueId.should.be.equal(0);
      });
      return it("second component type should have both componentId and uniqueId equal to 1", function() {
        type2.componentId.should.be.equal(1);
        return type2.uniqueId.should.be.equal(1);
      });
    });
  });

}).call(this);
