// Generated by CoffeeScript 1.3.3
(function() {
  var DummySystemHP, DummySystemMovement,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  window.ArtemisTests.DummySystemHP = {};

  window.ArtemisTests.DummySystemMovement = {};

  DummySystemHP = (function(_super) {

    __extends(DummySystemHP, _super);

    function DummySystemHP() {
      DummySystemHP.__super__.constructor.call(this, "DummyComponentHP");
    }

    DummySystemHP.prototype.initialize = function() {
      return this.dummyComponentHPMapper = new Artemis.ComponentMapper("DummyComponentHP", this.world);
    };

    DummySystemHP.prototype.processEntity = function(entity) {
      var dummyComponentHP;
      dummyComponentHP = this.dummyComponentHPMapper.get(entity);
      return dummyComponentHP.hp = 0;
    };

    return DummySystemHP;

  })(Artemis.EntityProcessingSystem);

  DummySystemMovement = (function(_super) {

    __extends(DummySystemMovement, _super);

    function DummySystemMovement() {
      DummySystemMovement.__super__.constructor.call(this, "DummyComponentPosition", "DummyComponentVelocity");
    }

    DummySystemMovement.prototype.initialize = function() {
      this.dummyComponentPositionMapper = new Artemis.ComponentMapper("DummyComponentPosition", this.world);
      return this.dummyComponentVelocityMapper = new Artemis.ComponentMapper("DummyComponentVelocity", this.world);
    };

    DummySystemMovement.prototype.processEntity = function(entity) {
      var position, velocity;
      velocity = this.dummyComponentVelocityMapper.get(entity);
      position = this.dummyComponentPositionMapper.get(entity);
      return position.x += velocity.velocity;
    };

    return DummySystemMovement;

  })(Artemis.EntityProcessingSystem);

  window.ArtemisTests.DummySystemHP = DummySystemHP;

  window.ArtemisTests.DummySystemMovement = DummySystemMovement;

}).call(this);
