// Generated by CoffeeScript 1.3.3
(function() {
  var DummyComponentHP, DummyComponentName, DummyComponentPosition,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  window.BragiTests = {};

  window.BragiTests.DummyComponentHP = {};

  window.BragiTests.DummyComponentPosition = {};

  window.BragiTests.DummyComponentName = {};

  DummyComponentHP = (function(_super) {

    __extends(DummyComponentHP, _super);

    function DummyComponentHP(hp) {
      this.hp = hp;
    }

    return DummyComponentHP;

  })(Bragi.Component);

  DummyComponentPosition = (function(_super) {

    __extends(DummyComponentPosition, _super);

    function DummyComponentPosition(x, y, z) {
      this.x = x;
      this.y = y;
      this.z = z;
    }

    return DummyComponentPosition;

  })(Bragi.Component);

  DummyComponentName = (function(_super) {

    __extends(DummyComponentName, _super);

    function DummyComponentName(name) {
      this.name = name;
    }

    return DummyComponentName;

  })(Bragi.Component);

  window.BragiTests.DummyComponentHP = DummyComponentHP;

  window.BragiTests.DummyComponentPosition = DummyComponentPosition;

  window.BragiTests.DummyComponentName = DummyComponentName;

}).call(this);
