// Generated by CoffeeScript 1.3.3
(function() {

  describe("World", function() {
    var world;
    world = null;
    describe("Instantiation", function() {
      before(function() {
        return world = new Bragi.EntityWorld();
      });
      it("should have an Entity Manager", function() {
        return world.entityManager.should.be.an["instanceof"](Bragi.EntityManager);
      });
      it("should have a System Manager", function() {
        return world.systemManager.should.be.an["instanceof"](Bragi.SystemManager);
      });
      it("should have a Tag Manager", function() {
        return world.tagManager.should.be.an["instanceof"](Bragi.TagManager);
      });
      return it("should have an empty array called deleted", function() {
        world.deleted.should.be.an["instanceof"](Array);
        return world.deleted.should.be.empty;
      });
    });
    describe("Creating an entity", function() {
      var entity;
      entity = null;
      before(function() {
        world = new Bragi.EntityWorld();
        return entity = world.createEntity();
      });
      it("should have created an entity", function() {
        return entity.should.be.an["instanceof"](Bragi.Entity);
      });
      return it("entity should have the world instance as property", function() {
        return entity.world.should.be.equal(world);
      });
    });
    return describe("Retrieving an entity", function() {
      var dummy, entity;
      entity = null;
      dummy = null;
      before(function() {
        world = new Bragi.EntityWorld();
        dummy = world.createEntity();
        return entity = world.getEntity(dummy.id);
      });
      it("should have an entity", function() {
        return entity.should.be.an["instanceof"](Bragi.Entity);
      });
      return it("entity should be equal to dummy", function() {
        return entity.should.be.equal(dummy);
      });
    });
  });

}).call(this);
