// Generated by CoffeeScript 1.3.3
(function() {

  describe("Entity Manager", function() {
    var world;
    world = null;
    before(function() {
      return world = new Bragi.World();
    });
    return describe("Instantiation", function() {
      var entity;
      entity = null;
      before(function() {
        return entity = new Bragi.Entity(world, 0);
      });
      it("should have the world instance as property", function() {
        return entity.world.should.be.an["instanceof"](Bragi.World);
      });
      it("should have an id equal to 0", function() {
        return entity.id.should.be.equal(0);
      });
      return it("should have an empty array called components", function() {
        entity.components.should.be.an["instanceof"](Array);
        return entity.components.should.be.empty;
      });
    });
  });

}).call(this);
